apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secrets
  namespace: opencloud
type: Opaque
stringData:
  STORAGE_USERS_DECOMPOSEDS3_ACCESS_KEY: REPLACE_WITH_S3_ACCESS_KEY
  STORAGE_USERS_DECOMPOSEDS3_SECRET_KEY: REPLACE_WITH_S3_SECRET_KEY
  IDM_ADMIN_PASSWORD: REPLACE_WITH_ADMIN_PASSWORD

